### ISSUE TITLE
website

### ISSUE THREAD

**Issue by kaihendry** [chgangaraju/terraform-aws-cloudfront-s3-website#1]
It's a shame that you don't use the S3 website feature.

 website {
    index_document = "index.html"
    error_document = "error.html"
}

Same issue as https://github.com/realglobe-Inc/terraform-aws-static-website/issues/5

**Comment by chgangaraju** [comment]
I am glad that you are using this module. s3 website feature is optional if you are already using CloudFront distribution. It's more secure by using with a custom domain without exposing the hosted s3 bucket name. 

Thank you for the feedback. I will add support for this.
