### ISSUE TITLE
Add bucket arn to output to facilitate the creation of IAM policies

### ISSUE THREAD

**Issue by Joao-Alves** [chgangaraju/terraform-aws-cloudfront-s3-website#5]
I am currently using the module and I am also creating an IAM user to manage the content of the bucket but I need to access the arn of the bucket

**Comment by Joao-Alves** [comment]
If want to create a pull request I would be able to add that parameter to the output

**Comment by chgangaraju** [comment]
Fixed in latest v1.2.3 version
